#!/usr/bin/env node
// Tiny local server for the review viewer. Serves the static viewer, Monaco from
// node_modules, and per-review data (manifest, comments, line-comments, reviewed
// state, file contents) for every review stored under .review/<key>/. The server
// is persistent and multi-review: start it once and leave it running — each new
// review generated by the skill/CLI shows up in the picker on refresh.
//
// Usage: node viewer/server.js [path/to/manifest.json] [--port 4173]
// With no argument it serves reviews from ./.review (relative to the cwd).
import http from 'node:http';
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseArgs, promisify } from 'node:util';
import { execFile } from 'node:child_process';
import { collectDiff } from '../src/diff.js';

const viewerDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(viewerDir, '..');
const monacoRoot = path.join(repoRoot, 'node_modules', 'monaco-editor', 'min');

const { values, positionals } = parseArgs({
  options: {
    port: { type: 'string', short: 'p' },
    repo: { type: 'string' },
    help: { type: 'boolean', short: 'h' },
  },
  allowPositionals: true,
});

if (values.help) {
  console.log(
    'Usage: node viewer/server.js [--repo <reviewed-repo>] [path/to/manifest.json] [--port 4173]\n' +
      '  --repo <dir>   the repository that was reviewed (its .review/ is served, and\n' +
      '                 git/gh run there). Defaults to the current directory.'
  );
  process.exit(0);
}

const basePort = parseInt(values.port ?? '4173', 10) || 4173;

// ---------- review roots & per-review paths ----------
// PROJECT_ROOT is the reviewed repo (its .review/ is served and git/gh run there);
// REVIEW_ROOT is PROJECT_ROOT/.review, holding one subdirectory per review (plus,
// for back-compat, an optional flat manifest.json directly inside it).
const { projectRoot: PROJECT_ROOT, reviewRoot: REVIEW_ROOT, initialKey } = resolveRoot();

function resolveRoot() {
  // Explicit --repo wins and is cwd-independent (what write-manifest.js prints).
  if (values.repo) {
    const root = path.resolve(values.repo);
    return { projectRoot: root, reviewRoot: path.join(root, '.review'), initialKey: null };
  }
  if (positionals[0]) {
    const abs = path.resolve(positionals[0]);
    const dir = path.dirname(abs); // folder containing the given manifest.json
    const parent = path.dirname(dir);
    if (path.basename(dir) === '.review') {
      return { projectRoot: parent, reviewRoot: dir, initialKey: '' };
    }
    if (path.basename(parent) === '.review') {
      return { projectRoot: path.dirname(parent), reviewRoot: parent, initialKey: path.basename(dir) };
    }
    return { projectRoot: path.dirname(dir), reviewRoot: dir, initialKey: '' };
  }
  return {
    projectRoot: process.cwd(),
    reviewRoot: path.resolve(process.cwd(), '.review'),
    initialKey: null,
  };
}

const VALID_KEY = /^[a-z0-9-]+$/i;

/** Absolute directory for a review key ('' = legacy flat manifest in REVIEW_ROOT). */
function reviewDirForKey(key) {
  if (!key) return REVIEW_ROOT;
  if (!VALID_KEY.test(key)) return null;
  const dir = path.join(REVIEW_ROOT, key);
  if (dir !== path.resolve(dir) || !dir.startsWith(REVIEW_ROOT + path.sep)) return null;
  return dir;
}

function pathsFor(key) {
  const dir = reviewDirForKey(key);
  if (!dir) return null;
  return {
    key,
    dir,
    manifest: path.join(dir, 'manifest.json'),
    comments: path.join(dir, 'comments.json'),
    lineComments: path.join(dir, 'line-comments.json'),
    reviewed: path.join(dir, 'reviewed.json'),
  };
}

async function readCurrent() {
  try {
    return JSON.parse(await fsp.readFile(path.join(REVIEW_ROOT, 'current.json'), 'utf8'));
  } catch {
    return null;
  }
}

/** Resolve the review key for a request: explicit ?review wins, else the active
 *  pointer (current.json), else the startup default, else legacy flat. */
async function keyForRequest(url) {
  const q = url.searchParams.get('review');
  if (q != null) {
    if (q === '') return '';
    return VALID_KEY.test(q) ? q : null;
  }
  if (initialKey != null) return initialKey;
  const cur = await readCurrent();
  return cur && cur.key ? cur.key : '';
}

const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.mjs': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.map': 'application/json; charset=utf-8',
  '.ttf': 'font/ttf',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
};

function sendJson(res, status, obj) {
  const body = JSON.stringify(obj);
  res.writeHead(status, {
    'Content-Type': 'application/json; charset=utf-8',
    'Cache-Control': 'no-store',
  });
  res.end(body);
}

async function sendFile(res, filePath) {
  try {
    const data = await fsp.readFile(filePath);
    res.writeHead(200, {
      'Content-Type': MIME[path.extname(filePath).toLowerCase()] ?? 'application/octet-stream',
      'Cache-Control': 'no-store',
    });
    res.end(data);
  } catch {
    res.writeHead(404, { 'Content-Type': 'text/plain' });
    res.end('Not found');
  }
}

/** Resolve a URL sub-path under a root dir, rejecting traversal. */
function safeJoin(root, subPath) {
  const resolved = path.resolve(root, '.' + path.posix.normalize('/' + subPath));
  if (resolved !== root && !resolved.startsWith(root + path.sep)) return null;
  return resolved;
}

async function readJsonFile(p, fallback) {
  try {
    return JSON.parse(await fsp.readFile(p, 'utf8'));
  } catch {
    return fallback;
  }
}

async function writeJsonFile(p, data) {
  await fsp.mkdir(path.dirname(p), { recursive: true });
  const tmp = p + '.tmp';
  await fsp.writeFile(tmp, JSON.stringify(data, null, 2) + '\n');
  await fsp.rename(tmp, p);
}

// ---------- reviews listing ----------
async function manifestMeta(mf) {
  const m = await readJsonFile(mf, null);
  if (!m || !Array.isArray(m.steps)) return null;
  const src = m.source || {};
  return {
    mode: src.mode || '',
    target: src.target || '',
    title: m.title || src.title || '',
    generatedAt: m.generatedAt || '',
    steps: m.steps.length,
    hasSummary: typeof m.summary === 'string' && m.summary.trim() !== '',
  };
}

async function listReviews() {
  const cur = await readCurrent();
  const activeKey = cur && cur.key ? cur.key : '';
  const reviews = [];
  let entries = [];
  try {
    entries = await fsp.readdir(REVIEW_ROOT, { withFileTypes: true });
  } catch {
    /* no .review yet */
  }
  for (const e of entries) {
    if (!e.isDirectory()) continue;
    const meta = await manifestMeta(path.join(REVIEW_ROOT, e.name, 'manifest.json'));
    if (meta) reviews.push({ key: e.name, ...meta });
  }
  // Legacy: a manifest.json directly under .review/ (key ''). Only surface it when
  // there are no per-diff subdirectories, to avoid a duplicate of a migrated review.
  if (!reviews.length) {
    const flat = await manifestMeta(path.join(REVIEW_ROOT, 'manifest.json'));
    if (flat) reviews.push({ key: '', ...flat });
  }

  reviews.sort((a, b) => String(b.generatedAt || '').localeCompare(String(a.generatedAt || '')));
  const active = reviews.some((r) => r.key === activeKey) ? activeKey : reviews[0]?.key ?? '';
  return { reviews, active };
}

async function writeCurrent(key) {
  const doc = { key, dir: path.join('.review', key), updatedAt: new Date().toISOString() };
  await writeJsonFile(path.join(REVIEW_ROOT, 'current.json'), doc);
}

// Delete a review's stored data. For a keyed review this removes its whole
// .review/<key>/ directory; for the legacy flat layout ('') it removes the flat
// files only (not the whole .review root). Fixes current.json if it pointed at
// the deleted review.
async function deleteReview(key) {
  const dir = reviewDirForKey(key);
  if (!dir) {
    const e = new Error('invalid review key');
    e.status = 400;
    throw e;
  }
  if (!key) {
    const flatFiles = [
      'manifest.json', 'chunks.json', 'review-notes.json',
      'comments.json', 'line-comments.json', 'reviewed.json', 'summary.md',
    ];
    for (const f of flatFiles) await fsp.rm(path.join(REVIEW_ROOT, f), { force: true });
  } else {
    await fsp.rm(dir, { recursive: true, force: true });
  }
  fileSources.delete(key);

  const cur = await readCurrent();
  if (cur && (cur.key ?? '') === key) {
    const { reviews } = await listReviews();
    if (reviews.length) await writeCurrent(reviews[0].key);
    else await fsp.rm(path.join(REVIEW_ROOT, 'current.json'), { force: true });
  }
  const listed = await listReviews();
  return { ok: true, deleted: key, ...listed };
}

// ---------- file source per review (for context + full-file view) ----------
const fileSources = new Map(); // key -> { readNew, readOld, listDir }
async function getFileSource(key) {
  if (fileSources.has(key)) return fileSources.get(key);
  const p = pathsFor(key);
  if (!p) throw new Error('invalid review');
  const manifest = await readJsonFile(p.manifest, null);
  if (!manifest) throw new Error('manifest not found');
  const src = manifest.source || {};
  let opts;
  if (src.mode === 'working') opts = { mode: 'working', cwd: PROJECT_ROOT };
  else if (src.mode === 'range') opts = { mode: 'range', range: src.target, cwd: PROJECT_ROOT };
  else if (src.mode === 'pr') {
    const m = String(src.target).match(/^([^/]+\/[^#]+)#(\d+)$/);
    if (!m) throw new Error(`cannot parse PR target "${src.target}"`);
    opts = { mode: 'pr', pr: m[2], repo: m[1], cwd: PROJECT_ROOT };
  } else {
    throw new Error(`unknown manifest source mode: ${src.mode}`);
  }
  const { source } = await collectDiff(opts);
  fileSources.set(key, source);
  return source;
}

async function readContext(key, file, start, end, side) {
  const source = await getFileSource(key);
  const content = side === 'old' ? await source.readOld(file) : await source.readNew(file);
  const all = content.split('\n');
  const s = Math.max(1, start);
  const e = Math.min(all.length, end);
  return { start: s, end: e, total: all.length, lines: s <= e ? all.slice(s - 1, e) : [] };
}

async function buildTree(key) {
  const p = pathsFor(key);
  const manifest = await readJsonFile(p.manifest, null);
  if (!manifest) throw new Error('manifest not found');
  const source = await getFileSource(key);
  const changed = new Map();
  manifest.steps.forEach((s, i) => {
    if (!changed.has(s.file)) changed.set(s.file, i);
  });
  const dirs = [...new Set([...changed.keys()].map((f) => f.split('/').slice(0, -1).join('/'))) ];
  dirs.sort();
  const folders = [];
  for (const dir of dirs) {
    let entries;
    try {
      entries = await source.listDir(dir);
    } catch {
      entries = [];
    }
    const files = entries
      .filter((e) => e.type === 'file')
      .map((e) => {
        const full = dir ? `${dir}/${e.name}` : e.name;
        return { name: e.name, path: full, changed: changed.has(full), stepIdx: changed.get(full) ?? null };
      })
      .sort((a, b) => a.name.localeCompare(b.name));
    folders.push({ dir, files });
  }
  return { folders };
}

// ---------- publishing to a GitHub PR (via the gh CLI) ----------
const execFileP = promisify(execFile);

async function gh(args) {
  try {
    const { stdout } = await execFileP('gh', args, { maxBuffer: 64 * 1024 * 1024 });
    return stdout;
  } catch (err) {
    if (err.code === 'ENOENT') {
      throw new Error('GitHub CLI (gh) not found — install it (brew install gh) and run `gh auth login`.');
    }
    const stderr = (err.stderr || '').toString().trim();
    const e = new Error(stderr || err.message);
    e.stderr = stderr;
    throw e;
  }
}

function parsePrTarget(target) {
  const m = String(target || '').match(/^([^/]+)\/([^#]+)#(\d+)$/); // owner/repo#123
  return m ? { slug: `${m[1]}/${m[2]}`, num: m[3] } : null;
}

async function postPrComment({ slug, num, commitId, body, file, line, side }) {
  const args = [
    'api',
    '--method',
    'POST',
    `repos/${slug}/pulls/${num}/comments`,
    '-f',
    `body=${body}`,
    '-f',
    `commit_id=${commitId}`,
    '-f',
    `path=${file}`,
  ];
  if (line != null) args.push('-F', `line=${line}`, '-f', `side=${side}`);
  else args.push('-f', 'subject_type=file');
  args.push('--jq', '.html_url');
  return (await gh(args)).trim();
}

async function publishReview(manifest, comments, lineComments) {
  const pr = manifest.source && manifest.source.mode === 'pr'
    ? parsePrTarget(manifest.source.target)
    : null;
  if (!pr) {
    const e = new Error('Publishing requires a PR-mode manifest (generate it with --pr).');
    e.status = 400;
    throw e;
  }
  const headSha = (await gh(['api', `repos/${pr.slug}/pulls/${pr.num}`, '--jq', '.head.sha'])).trim();
  const stepById = new Map(manifest.steps.map((s) => [s.id, s]));
  const results = [];

  async function post(idLabel, file, body, line, side) {
    const common = { slug: pr.slug, num: pr.num, commitId: headSha, body, file };
    try {
      const url = await postPrComment({ ...common, line, side });
      results.push({ id: idLabel, status: 'posted', url });
    } catch {
      try {
        const url = await postPrComment({ ...common, line: null });
        results.push({ id: idLabel, status: 'posted-file', url });
      } catch (err2) {
        results.push({ id: idLabel, status: 'failed', reason: (err2.stderr || err2.message || '').slice(0, 300) });
      }
    }
  }

  for (const [id, text] of Object.entries(comments || {})) {
    if (!text || !text.trim()) continue;
    const step = stepById.get(id);
    if (!step) {
      results.push({ id, status: 'skipped', reason: 'no matching step in manifest' });
      continue;
    }
    const deleted = step.changeKind === 'deleted';
    const side = deleted ? 'LEFT' : 'RIGHT';
    const line = deleted ? step.oldStartLine || step.startLine : step.endLine;
    await post(id, step.file, text, line, side);
  }

  for (const [id, byLine] of Object.entries(lineComments || {})) {
    const step = stepById.get(id);
    if (!step) {
      results.push({ id, status: 'skipped', reason: 'no matching step in manifest' });
      continue;
    }
    for (const [lineStr, text] of Object.entries(byLine || {})) {
      if (!text || !text.trim()) continue;
      await post(`${step.file}:${lineStr}`, step.file, text, Number(lineStr), 'RIGHT');
    }
  }

  const posted = results.filter((r) => r.status.startsWith('posted')).length;
  const failed = results.filter((r) => r.status === 'failed').length;
  return { ok: failed === 0, target: manifest.source.target, posted, failed, results };
}

function readBody(req, limit = 1024 * 1024) {
  return new Promise((resolve, reject) => {
    let size = 0;
    const parts = [];
    req.on('data', (d) => {
      size += d.length;
      if (size > limit) {
        reject(new Error('body too large'));
        req.destroy();
        return;
      }
      parts.push(d);
    });
    req.on('end', () => resolve(Buffer.concat(parts).toString('utf8')));
    req.on('error', reject);
  });
}

// Resolve the review paths for a request, or send an error and return null.
async function paths(req, res, url) {
  const key = await keyForRequest(url);
  if (key === null) {
    sendJson(res, 400, { error: 'invalid review key' });
    return null;
  }
  return pathsFor(key);
}

const server = http.createServer(async (req, res) => {
  const url = new URL(req.url, 'http://localhost');
  const pathname = decodeURIComponent(url.pathname);

  try {
    if (pathname === '/api/reviews' && req.method === 'GET') {
      sendJson(res, 200, await listReviews());
      return;
    }

    if (pathname === '/api/review' && req.method === 'DELETE') {
      const key = await keyForRequest(url);
      if (key === null) return sendJson(res, 400, { error: 'invalid review key' });
      try {
        sendJson(res, 200, await deleteReview(key));
      } catch (err) {
        sendJson(res, err.status || 500, { error: err.message });
      }
      return;
    }

    if (pathname === '/api/manifest' && req.method === 'GET') {
      const p = await paths(req, res, url);
      if (!p) return;
      try {
        const data = await fsp.readFile(p.manifest, 'utf8');
        res.writeHead(200, { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store' });
        res.end(data);
      } catch {
        sendJson(res, 404, {
          error: `manifest not found at ${p.manifest} — generate one first (skill or bin/generate-manifest.js)`,
        });
      }
      return;
    }

    if (pathname === '/api/comments' && req.method === 'GET') {
      const p = await paths(req, res, url);
      if (!p) return;
      sendJson(res, 200, await readJsonFile(p.comments, {}));
      return;
    }

    if (pathname === '/api/comments' && (req.method === 'PUT' || req.method === 'POST')) {
      const p = await paths(req, res, url);
      if (!p) return;
      const body = JSON.parse(await readBody(req));
      if (typeof body.id !== 'string') {
        sendJson(res, 400, { error: 'expected {id: string, text: string}' });
        return;
      }
      const comments = await readJsonFile(p.comments, {});
      const text = String(body.text ?? '');
      if (text.trim() === '') delete comments[body.id];
      else comments[body.id] = text;
      await writeJsonFile(p.comments, comments);
      sendJson(res, 200, { ok: true, saved: text.trim() !== '' });
      return;
    }

    if (pathname === '/api/line-comments' && req.method === 'GET') {
      const p = await paths(req, res, url);
      if (!p) return;
      sendJson(res, 200, await readJsonFile(p.lineComments, {}));
      return;
    }

    if (pathname === '/api/line-comments' && (req.method === 'PUT' || req.method === 'POST')) {
      const p = await paths(req, res, url);
      if (!p) return;
      const body = JSON.parse(await readBody(req));
      if (typeof body.id !== 'string' || !Number.isInteger(body.line)) {
        sendJson(res, 400, { error: 'expected {id: string, line: int, text: string}' });
        return;
      }
      const data = await readJsonFile(p.lineComments, {});
      const text = String(body.text ?? '');
      const forStep = data[body.id] || {};
      if (text.trim() === '') delete forStep[body.line];
      else forStep[body.line] = text;
      if (Object.keys(forStep).length) data[body.id] = forStep;
      else delete data[body.id];
      await writeJsonFile(p.lineComments, data);
      sendJson(res, 200, { ok: true, saved: text.trim() !== '' });
      return;
    }

    if (pathname === '/api/context' && req.method === 'GET') {
      const key = await keyForRequest(url);
      if (key === null) return sendJson(res, 400, { error: 'invalid review key' });
      const file = url.searchParams.get('file');
      const start = parseInt(url.searchParams.get('start'), 10);
      const end = parseInt(url.searchParams.get('end'), 10);
      const side = url.searchParams.get('side') === 'old' ? 'old' : 'new';
      if (!file || !Number.isInteger(start) || !Number.isInteger(end)) {
        sendJson(res, 400, { error: 'expected file, start, end query params' });
        return;
      }
      try {
        sendJson(res, 200, await readContext(key, file, start, end, side));
      } catch (err) {
        sendJson(res, 500, { error: err.message });
      }
      return;
    }

    if (pathname === '/api/tree' && req.method === 'GET') {
      const key = await keyForRequest(url);
      if (key === null) return sendJson(res, 400, { error: 'invalid review key' });
      try {
        sendJson(res, 200, await buildTree(key));
      } catch (err) {
        sendJson(res, 500, { error: err.message });
      }
      return;
    }

    if (pathname === '/api/file' && req.method === 'GET') {
      const key = await keyForRequest(url);
      if (key === null) return sendJson(res, 400, { error: 'invalid review key' });
      const file = url.searchParams.get('file');
      const side = url.searchParams.get('side') === 'old' ? 'old' : 'new';
      if (!file) {
        sendJson(res, 400, { error: 'expected file query param' });
        return;
      }
      try {
        const source = await getFileSource(key);
        const content = side === 'old' ? await source.readOld(file) : await source.readNew(file);
        sendJson(res, 200, { file, content, lineCount: content.split('\n').length });
      } catch (err) {
        sendJson(res, 500, { error: err.message });
      }
      return;
    }

    if (pathname === '/api/reviewed' && req.method === 'GET') {
      const p = await paths(req, res, url);
      if (!p) return;
      sendJson(res, 200, await readJsonFile(p.reviewed, {}));
      return;
    }

    if (pathname === '/api/reviewed' && (req.method === 'PUT' || req.method === 'POST')) {
      const p = await paths(req, res, url);
      if (!p) return;
      const body = JSON.parse(await readBody(req));
      if (typeof body.id !== 'string') {
        sendJson(res, 400, { error: 'expected {id: string, reviewed: bool}' });
        return;
      }
      const data = await readJsonFile(p.reviewed, {});
      if (body.reviewed) data[body.id] = true;
      else delete data[body.id];
      await writeJsonFile(p.reviewed, data);
      sendJson(res, 200, { ok: true, reviewed: !!body.reviewed });
      return;
    }

    if (pathname === '/api/publish' && req.method === 'POST') {
      const p = await paths(req, res, url);
      if (!p) return;
      const manifest = await readJsonFile(p.manifest, null);
      if (!manifest) {
        sendJson(res, 404, { error: 'manifest not found' });
        return;
      }
      const comments = await readJsonFile(p.comments, {});
      const lineComments = await readJsonFile(p.lineComments, {});
      const hasStep = Object.values(comments).some((t) => t && t.trim());
      const hasLine = Object.values(lineComments).some(
        (byLine) => byLine && Object.values(byLine).some((t) => t && t.trim())
      );
      if (!hasStep && !hasLine) {
        sendJson(res, 400, { error: 'no comments to publish' });
        return;
      }
      try {
        sendJson(res, 200, await publishReview(manifest, comments, lineComments));
      } catch (err) {
        sendJson(res, err.status || 500, { error: err.message });
      }
      return;
    }

    if (pathname.startsWith('/vendor/monaco/')) {
      const target = safeJoin(monacoRoot, pathname.slice('/vendor/monaco/'.length));
      if (!target) {
        res.writeHead(403).end();
        return;
      }
      await sendFile(res, target);
      return;
    }

    const rel = pathname === '/' ? 'index.html' : pathname.slice(1);
    const target = safeJoin(viewerDir, rel);
    if (!target) {
      res.writeHead(403).end();
      return;
    }
    await sendFile(res, target);
  } catch (err) {
    sendJson(res, 500, { error: err.message });
  }
});

function listen(port, attemptsLeft) {
  server.once('error', (err) => {
    if (err.code === 'EADDRINUSE' && attemptsLeft > 0) {
      console.error(`port ${port} is in use, trying ${port + 1}…`);
      listen(port + 1, attemptsLeft - 1);
    } else {
      console.error(`error: ${err.message}`);
      process.exit(1);
    }
  });
  server.listen(port, '127.0.0.1', () => {
    console.log(`BelAir review viewer`);
    console.log(`  repo:    ${PROJECT_ROOT}`);
    if (fs.existsSync(REVIEW_ROOT)) {
      console.log(`  reviews: ${REVIEW_ROOT}`);
    } else {
      console.log(`  reviews: ${REVIEW_ROOT}  (NOT FOUND)`);
      console.log(`  → No .review here. Run this from the reviewed repo, or pass --repo <that repo>.`);
    }
    if (!fs.existsSync(monacoRoot)) {
      console.log(`  WARNING: monaco-editor not found — run \`npm install\` in ${repoRoot}`);
    }
    console.log(`  → http://localhost:${port}`);
  });
}

listen(basePort, 10);
